config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "tournaments#index"
  resources :tournaments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tournament.rb
class Tournament < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: %i[show edit update destroy]

  def index
    @tournaments = Tournament.all
  end

  def show
  end

  def new
    @tournament = Tournament.new
  end

  def edit
  end

  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to tournament_url(@tournament), notice: "Tournament was successfully created." }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to tournament_url(@tournament), notice: "Tournament was successfully updated." }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: "Tournament was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  def tournament_params
    params.require(:tournament).permit(:name, :starts_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tourney</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tournaments/_form.html.erb
<%= form_with(model: tournament) do |form| %>
  <% if tournament.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
        <% tournament.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :starts_at, style: "display: block" %>
    <%= form.datetime_field :starts_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tournaments/_tournament.html.erb
<div id="<%= dom_id tournament %>">
  <p>
    <strong>Name:</strong>
    <%= tournament.name %>
  </p>

  <p>
    <strong>Starts at:</strong>
    <%= tournament.starts_at %>
  </p>

</div>

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render "form", tournament: @tournament %>

<br>

<div>
  <%= link_to "Show this tournament", @tournament %> |
  <%= link_to "Back to tournaments", tournaments_path %>
</div>

app/views/tournaments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tournaments</h1>

<div id="tournaments">
  <% @tournaments.each do |tournament| %>
    <%= render tournament %>
    <p>
      <%= link_to "Show this tournament", tournament %>
    </p>
  <% end %>
</div>

<%= link_to "New tournament", new_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render "form", tournament: @tournament %>

<br>

<div>
  <%= link_to "Back to tournaments", tournaments_path %>
</div>

app/views/tournaments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tournament %>

<div>
  <%= link_to "Edit this tournament", edit_tournament_path(@tournament) %> |
  <%= link_to "Back to tournaments", tournaments_path %>

  <%= button_to "Destroy this tournament", @tournament, method: :delete %>
</div>